version: "3.1"

services:
  mongo:
    image: mongo:3
    container_name: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=clean-node-api
  api:
    container_name: clean-node-api
    image: node:16
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "npm install --only=prod && npm start"
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports: 
      - "5000:5000"
    links:
      - mongo